// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASfJyAhHL8OBMEeH_qT5cHJ5WgxigBaRs',
    appId: '1:368863566430:web:d65afb63ada51ba66132cf',
    messagingSenderId: '368863566430',
    projectId: 'kupid-e0caa',
    authDomain: 'kupid-e0caa.firebaseapp.com',
    storageBucket: 'kupid-e0caa.firebasestorage.app',
    measurementId: 'G-9P6DRHBECM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5GomxBM8-xXjibL5uzjoykgxanX_JJYI',
    appId: '1:368863566430:android:d71eeb40aedc7dff6132cf',
    messagingSenderId: '368863566430',
    projectId: 'kupid-e0caa',
    storageBucket: 'kupid-e0caa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB87iV0kG3HdIUkvvW50cb63zB_D-HhyPQ',
    appId: '1:368863566430:ios:78a683585ae634cc6132cf',
    messagingSenderId: '368863566430',
    projectId: 'kupid-e0caa',
    storageBucket: 'kupid-e0caa.firebasestorage.app',
    iosBundleId: 'com.example.kupid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB87iV0kG3HdIUkvvW50cb63zB_D-HhyPQ',
    appId: '1:368863566430:ios:78a683585ae634cc6132cf',
    messagingSenderId: '368863566430',
    projectId: 'kupid-e0caa',
    storageBucket: 'kupid-e0caa.firebasestorage.app',
    iosBundleId: 'com.example.kupid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASfJyAhHL8OBMEeH_qT5cHJ5WgxigBaRs',
    appId: '1:368863566430:web:74f62a4f6b2fcce16132cf',
    messagingSenderId: '368863566430',
    projectId: 'kupid-e0caa',
    authDomain: 'kupid-e0caa.firebaseapp.com',
    storageBucket: 'kupid-e0caa.firebasestorage.app',
    measurementId: 'G-WMJHKTNQWZ',
  );
}
